Imported new upstream sources - rancid-3.5.1.tar.gz

diff --git a/bin/rancid-run.in b/bin/rancid-run.in
--- a/bin/rancid-run.in
+++ b/bin/rancid-run.in
@@ -1,6 +1,6 @@
 #! /bin/sh
 ##
-## $Id: rancid-run.in 3018 2015-01-11 05:51:49Z heas $
+## $Id: rancid-run.in 3448 2016-08-15 21:30:19Z heas $
 ##
 ## @PACKAGE@ @VERSION@
 ## Copyright (c) @COPYYEARS@ by Terrapin Communications, Inc.
@@ -123,8 +123,11 @@ elif [ "$LIST_OF_GROUPS" = "" ] ; then
     exit 1
 fi
 
+# LOGDIR location
+LOGDIR=${LOGDIR:=$BASEDIR/logs};
 if [ ! -d $LOGDIR ] ; then
-    mkdir $LOGDIR || (echo "Could not create log directory: $LOGDIR"; exit 1)
+    mkdir -p $LOGDIR || (echo "Could not create log directory: $LOGDIR" >&2;
+			 exit 1)
 fi
 
 for GROUP in $LIST_OF_GROUPS
@@ -145,7 +148,12 @@ do
 	    if [ "X$LOCKTIME" = "X" ] ; then
 		LOCKTIME=4
 	    fi
-	    @PERLV@ -e "\$t = (stat(\"$LOCKFILE\"))[9]; print \"OLD\\n\" if (time() - \$t >= $LOCKTIME*60*60);" > $TMPDIR/.$GROUP.old
+	    GRPOLDFILE=`mktemp -q $TMPDIR/.$GROUP.XXXXXX`
+	    if [ $? -ne 0 ] ; then
+		echo "Could not create temporary file for error email" >&2
+		exit 1
+	    fi
+	    @PERLV@ -e "\$t = (stat(\"$LOCKFILE\"))[9]; print \"OLD\\n\" if (time() - \$t >= $LOCKTIME*60*60);" > $GRPOLDFILE
 	    if [ -s $TMPDIR/.$GROUP.old ]
 	    then
 		(
@@ -160,14 +168,16 @@ do
 rancid $GROUP hung on `hostname`?  Old lockfile still exists:
 `ls -l $LOCKFILE`
 END
-		) | @SENDMAIL@ -t $MAILOPTS
+		) | $SENDMAIL -t $MAILOPTS
 	    fi
-	    rm -f $TMPDIR/.$GROUP.old
+	    rm -f $GRPOLDFILE
+	    exit 1
 	else
 	    trap 'rm -fr $LOCKFILE;exit 1' 1 2 3 6 10 15
-	    touch $LOCKFILE
+	    perl -e 'use POSIX;sysopen(FH, $ARGV[1], O_RDWR|O_CREAT|O_EXCL, 0660) or exit 1;print FH "$ARGV[0]\n";' -- $$ $LOCKFILE
 	    if [ $? -eq 0 ] ; then
 		control_rancid $CR_ARGV $GROUP
+		trap ''  1 2 3 6 10 15
 		rm -f $LOCKFILE
 	    fi
 	    trap ''  1 2 3 6 10 15
